apiVersion: v1
kind: Service
metadata:
  name: raspk3s-service
spec:
  selector:
    app: raspk3s-app
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: raspk3s-app
spec:
  selector:
    matchLabels:
      app: raspk3s-app
  replicas: 4
  template:
    metadata:
      labels:
        app: raspk3s-app
    spec:
      containers:
      - name: raspk3s
        image: pavelzagalsky/raspk3s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80